name: fancy_glassmorphism
description: A new Flutter package with Fancy Glass Morphism.
version: 0.0.1
homepage: https://github.com/yousufCse/fancy_glassmorphism.git

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
